services:
  cyber-eyes:
    build: .
    image: cyber-eyes:latest
    container_name: cyber-eyes
    ports:
      - "8006:8006"
    volumes:
      - ./workspace:/workspace
    environment:
      - GATEWAY_PROTO=https
      # - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
